// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6J8ovifrksmBmbYw974WVNnynwIfEZw',
    appId: '1:774878334004:web:fb94c52bdfa33cf2ad8e61',
    messagingSenderId: '774878334004',
    projectId: 'fir-app-907d3',
    authDomain: 'fir-app-907d3.firebaseapp.com',
    storageBucket: 'fir-app-907d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAet4_KKIxBgSrCyNYWpBcyzefpy-kjvZ0',
    appId: '1:774878334004:android:7ea2e056162b2c4ead8e61',
    messagingSenderId: '774878334004',
    projectId: 'fir-app-907d3',
    storageBucket: 'fir-app-907d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf262ZSpwWvfDK0kCBwBIog5rTZCNbo8w',
    appId: '1:774878334004:ios:76ff5aa11146c30bad8e61',
    messagingSenderId: '774878334004',
    projectId: 'fir-app-907d3',
    storageBucket: 'fir-app-907d3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf262ZSpwWvfDK0kCBwBIog5rTZCNbo8w',
    appId: '1:774878334004:ios:76ff5aa11146c30bad8e61',
    messagingSenderId: '774878334004',
    projectId: 'fir-app-907d3',
    storageBucket: 'fir-app-907d3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO6J8ovifrksmBmbYw974WVNnynwIfEZw',
    appId: '1:774878334004:web:2d25cd3bef403b37ad8e61',
    messagingSenderId: '774878334004',
    projectId: 'fir-app-907d3',
    authDomain: 'fir-app-907d3.firebaseapp.com',
    storageBucket: 'fir-app-907d3.firebasestorage.app',
  );
}
