package com.Grp._8.backend.entities.enums;

public enum Department {
    GENERAL_PHYSICIAN,
    PEDIATRICIAN,
    GYNECOLOGIST_OBSTETRICIAN,
    GENERAL_SURGEON,
    ORTHOPEDIC_SURGEON,
    CARDIOLOGIST,
    NEUROLOGIST,
    GASTROENTEROLOGIST,
    NEPHROLOGIST,
    PULMONOLOGIST,
    ENDOCRINOLOGIST,
    ONCOLOGIST,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    PATHOLOGIST,
    EMERGENCY_MEDICINE_PHYSICIAN,
    DERMATOLOGIST,
    PSYCHIATRIST,
    ENT_SURGEON,
    UROLOGIST,
    OPHTHALMOLOGIST
}